- name: create folder {{ folder_web }}
  file:
    path: /var/www/{{ main_domain_name }}/{{ folder_web }}/
    state: directory
    mode: '0755'

- name: install git
  apt:
    name: git

- name: Deploy sample html file 
  git:
    repo: '{{ github_repo }}'
    dest: /var/www/{{ main_domain_name }}/{{ folder_web }}/
    
- name: copy wpconfig
  template:
    src: wp-config.php
    dest: /var/www/{{ main_domain_name }}/{{ folder_web }}/
  

- name: Run SQL commands to create database {{ wp_db_name }}
  mysql_db:
        login_host: "{{ wp_db_hostname }}"
        login_password: "{{ wp_db_password }}"
        login_user: "{{ wp_db_user }}"
        login_port: "3306"
        name: "{{ wp_db_name }}"
        state: present
